### ISSUE TITLE
Probe for SpotBugs

### ISSUE THREAD

**Issue by jleon33** [jenkins-infra/plugin-health-scoring#151]
we should implement a probe to see if SpotBugs is configured/enabled

**Comment by impact-maker** [comment]
@jleon33 @alecharp  I wanted to try and implement this probe.

**Comment by alecharp** [comment]
@impact-maker please submit a complete pull request, with code coverage.

**Comment by yashre-bh** [comment]
@alecharp is this a beginner friendly issue? if yes, can you lead me as to where to get started?
