### ISSUE TITLE
Plugin publication can be stopped by the update-center

### ISSUE THREAD

**Issue by alecharp** [jenkins-infra/plugin-health-scoring#178]
It happens that a plugin's publication is stopped at the update-center level. 
There are many reasons why this can happen. Latest to date is `ascii-magican` (https://github.com/jenkins-infra/update-center2/pull/675).

We cannot get any reason why this happens from the update-center, but we can have a probe which will use the update-center content and detect that a plugin is not present there and mark the plugin as such. 

This could contribute to the [`DeprecatedPluginScoring`](https://github.com/jenkins-infra/plugin-health-scoring/blob/main/src/main/java/io/jenkins/pluginhealth/scoring/scores/DeprecatedPluginScoring.java).

**Comment by jleon33** [comment]
Very interesting probe that I was unaware of. 👍

**Comment by Jagrutiti** [comment]
Hey @alecharp 

This sounds an interesting issue to understand the probes.

Could you tell me how to proceed?

Shall I write a test case to expose the issue? 

How do I recreate the issue in my local?

**Comment by alecharp** [comment]
Sure thing @Jagrutiti. 

First, the condition of the probe: 
 - it does not require a release to be updated
 - it does not require a code change to be updated

Then, if you provide a `ProbeContext` with an `UpdateCenter` which doesn't contain the plugin in the map of `plugins`, then your probe should return a `FAILURE`, meaning the plugin is no longer published. If the plugin can be located in the map, then the probe should return a `SUCCESS` as the plugin is still published.

For the [`DeprecatedPluginScoring`](https://github.com/jenkins-infra/plugin-health-scoring/blob/main/src/main/java/io/jenkins/pluginhealth/scoring/scores/DeprecatedPluginScoring.java), for the moment, it's only checking the presence of the DeprecatedPluginProbe result. But it has now also to check the presence of the new probe.

I hope this clarify the requirements.

**Comment by Jagrutiti** [comment]
Hey @alecharp 

> Then, if you provide a `ProbeContext` with an `UpdateCenter` which doesn't contain the plugin in the map of `plugins`, then your probe should return a `FAILURE` ...

I see a [ProbeContext](https://github.com/Jagrutiti/plugin-health-scoring/blob/c51f543600de0c82d0d116bffa954683d531de05/src/main/java/io/jenkins/pluginhealth/scoring/probes/ProbeContext.java#L47) already exists. `pluginName` and `updateCenter` are two parameters passed to it as well.

How do I:

> If the plugin can be located in the map...

locate the plugin in the map? By map do you mean the JSON in the database?

Shall I write method for this? Or modify the existing `ProbeContext`?

**Comment by alecharp** [comment]
> locate the plugin in the map? By map do you mean the JSON in the database?

No I mean the map of plugins in the Update Center.

> Shall I write method for this? Or modify the existing ProbeContext?

You don't need.

**Comment by alecharp** [comment]
Because #205 is now merged, I'm closing this.
