### ISSUE TITLE
Extending capabilities of Dependabot Probe 

### ISSUE THREAD

**Issue by impact-maker** [jenkins-infra/plugin-health-scoring#192]
Description
We would want to extend the capabilities of dependebot probe which would help the maintainers in the similar way they use updateCLI

**Comment by alecharp** [comment]
What exactly is your issue with that one? Please provide a description to your issue.

**Comment by impact-maker** [comment]
@alecharp  Wanted to work on this enhancement and have a discussion with all the experienced team members

**Comment by alecharp** [comment]
Do you mean that we should check for maintainers using `updatecli` as we do for maintainers using `dependabot`?

**Comment by lemeurherve** [comment]
> Do you mean that we should check for maintainers using updatecli as we do for maintainers using dependabot?

f it's the case I would also extend it to the use of renovabot (the third bot frequently used in Jenkins repositories)

**Comment by alecharp** [comment]
I'm surprise. Do you have example of plugins repository using `updatecli` or `renovabot`? Because, the documentation [here](https://www.jenkins.io/doc/developer/plugin-development/dependency-management/) is only mentioning `dependabot`.

**Comment by alecharp** [comment]
@impact-maker could you answer my question from my last comment? If there is no other tool used to manage the dependency update, I don't see why we need to keep this issue open. 

Thanks.
