### ISSUE TITLE
Improve documentation on `Probe` class

### ISSUE THREAD

**Issue by alecharp** [jenkins-infra/plugin-health-scoring#214]
The `Probe` class methods aren't clearly documented enough. As this is an important part of the project, we need to have clearer documentation on them, to understand why they are needed, how they are used and what should be their behavior.

The same is true for `Scoring` class which has absolutely no documentation.

# Requirements

- [ ] `Probe#key()` is documented
- [ ] `Probe#getDescription()` is documented
- [ ] `Probe#requiresRelease()` is documented
- [ ] `Probe#isSourceCodeRelated()` is documented
- [ ] All methods in `Scoring` have been documented

**Comment by Madhupatel08** [comment]
I would love to work on this issue. Can I have this assigned to me?
