### ISSUE TITLE
Highlight project improvement 

### ISSUE THREAD

**Issue by alecharp** [jenkins-infra/plugin-health-scoring#23]
Due to the current state of the project, it is difficult for anyone outside the developers team to know what the project is doing, how it is evolving.

We need to find a way to show the list of probes currently implemented on the project. We could also show a page with the result of the execution of each probes on the plugins we know.

**Comment by dheerajodha** [comment]
What do you mean by "page"? is it just a markdown file with a hardcoded list of current probes (which I can understand would not be scalable) or some page that takes values dynamically from our project (something like JSP? maybe...)?

**Comment by alecharp** [comment]
I had a JSP in mind. However, if we could generate a static page which could be generated once and stored by the CI, it could be great as well.

**Comment by alecharp** [comment]
With #27 and the `probe` label here on the GitHub repository, we have technical ways to see the current status as well as the short-term plan on this project concerning the probe implementation.

For a larger view of the plan, we would need a page listing more long-term plans but I don't see any way to maintain that correctly.

I'm considering this as resolved, but we might want to reconsider this later on.
