### ISSUE TITLE
Add a probe for the Jenkins security scan workflow

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/plugin-health-scoring#257]
### Description

It would be nice to have a probe for the Jenkins security scan, https://github.com/search?q=org%3Ajenkinsci+%22uses%3A+jenkins-infra%2Fjenkins-security-scan%22&type=code

I included the workflow in the template new plugin hosting requests use, therefore the overall usage will increase within new plugins 🎉

**Comment by dheerajodha** [comment]
@alecharp should we add the [friendly](https://github.com/jenkins-infra/plugin-health-scoring/issues?q=is%3Aissue+is%3Aopen+label%3Afriendly) label to this issue?

**Comment by amanfangeria980** [comment]
Hey @NotMyFault, can you please explain me what is a probe and what do I have to do in that probe? I'm new to open-source

**Comment by amanfangeria980** [comment]
Hey @alecharp thanks for explaining, but what do we have to add in those files or should I just add a probe block, I mean what work to do under that probe?

**Comment by dheerajodha** [comment]
@amanfangeria980 You do not have to add anything to the file. As Adrien explained, the probe should look inside these files and search for the presence of the line `uses: jenkins-infra/jenkins-security-scan/.github/workflows/jenkins-security-scan.yaml`.

Like for example, in the `JenkinsfileProbe` the probe searches for a file named `Jenkinsfile` inside the GitHub repository, [please see here](https://github.com/jenkins-infra/plugin-health-scoring/blob/main/core/src/main/java/io/jenkins/pluginhealth/scoring/probes/JenkinsfileProbe.java#L48). Does this help you to understand what needs to be done? or do you want me to elaborate more on some parts?

**Comment by amanfangeria980** [comment]
Hi @dheerajodha, thanks for describing the issue in a friendly manner, I got the gist of it, here's what I got to knew,

I have to create a similar file like JenkinsfileProbe which searches for the "uses: jenkins-infra/jenkins-security-scan/.github/workflows/jenkins-security-scan.yaml" and returns boolean.

**Comment by amanfangeria980** [comment]
If this is right, could you assign this issue to me, I would like to work upon it.

**Comment by alecharp** [comment]
> I have to create a similar file like JenkinsfileProbe which searches for the "uses: jenkins-infra/jenkins-security-scan/.github/workflows/jenkins-security-scan.yaml" and returns boolean.

This is not really what a probe is supposed to return. Please see https://github.com/jenkins-infra/plugin-health-scoring/pull/315.

> If this is right, could you assign this issue to me, I would like to work upon it.

Sure, but opening a pull request is the best way to show that you are working on this.

**Comment by amanfangeria980** [comment]
Thanks @alecharp, I will work upon this.

**Comment by amanfangeria980** [comment]
Also, @dheerajodha , do share your insights on my part.

**Comment by Jagrutiti** [comment]
Hey @alecharp 

Summarizing the steps I understood,


- `getWorkflowDefinition()` will the find file to look for in jenkins repository inside `.github/workflows`

- Once that file is found I need to find `uses: jenkins-infra/jenkins-security-scan/.github/workflows/<security-scan-file-name>.yaml` in the file returned by `getWorkflowDefinition()`?

- If `uses: jenkins-infra/jenkins-security-scan/.github/workflows/<security-scan-file-name>.yaml` is found, ProbeResult will be success, otherwise failure? 


Is tihs the correct way to proceed?

**Comment by dheerajodha** [comment]
@Jagrutiti I think Adrien proposes to identify the common tasks performed in these similar probes (ContinuousDeliveryProbe and this SecurityScanProbe) and put them in a new `AbstractGitHubWorkflowProbe` file in a way to help us eliminate the duplicate code.

Can you try to look at the code of `ContinuousDeliveryProbe` and group its code into different sections, and find out which section is generic and can be put in a generic file and which one needs to be present there?

**Comment by Jagrutiti** [comment]
What is `JEP-229`?  probe? I do not see any probe with that name.

**Comment by Jagrutiti** [comment]
To me, it seems like we are interested in `WorkflowJobDefinition()`. This is common for `ContinuousDeliveryProbe` and the new `SecurityScanProbe`.

**Comment by dheerajodha** [comment]
> What is JEP-229? probe? I do not see any probe with that name.

https://plugin-health.jenkins.io/probes `jep-229` probe == `ContinuousDeliveryProbe`

**Comment by dheerajodha** [comment]
> To me, it seems like we are interested in WorkflowJobDefinition(). This is common for ContinuousDeliveryProbe and the new SecurityScanProbe.

I'm confused sorry, so which part of the code from [JEP-229 probe](https://github.com/jenkins-infra/plugin-health-scoring/blob/main/core/src/main/java/io/jenkins/pluginhealth/scoring/probes/ContinuousDeliveryProbe.java#L53-L84) should stay in it and what part of it, which are the common steps, can be moved to a generic file? so it could be reused by similar probes.

**Comment by Jagrutiti** [comment]
This part looks similar to in JEP-229 probe.

https://github.com/jenkins-infra/plugin-health-scoring/blob/main/core/src/main/java/io/jenkins/pluginhealth/scoring/probes/ContinuousDeliveryProbe.java#LL64C1-L80C5

**Comment by dheerajodha** [comment]
Yes, but the main difference between these kinds of probes is [this line](https://github.com/jenkins-infra/plugin-health-scoring/blob/8f5da4f2ce554f1c608c63b8942a906c3ccf0459/core/src/main/java/io/jenkins/pluginhealth/scoring/probes/ContinuousDeliveryProbe.java#L77) (line 77), where we specify the workflow used by the job. This line 77 is the main part specific to that probe only, the rest of the code can be extracted and put into another file.

And this is the foundation of what Adrien suggested above if I'm not wrong (@alecharp please correct me if I'm wrong).

So, [this section of the code](https://github.com/jenkins-infra/plugin-health-scoring/blob/main/core/src/main/java/io/jenkins/pluginhealth/scoring/probes/ContinuousDeliveryProbe.java#L53-L84) can be described generally in the following way:
* Traverse through all the files present in the `.github/workflows` folder.
* For each of the files, read the content within the `jobs` field, and look for the value of the `uses` field.
* Check if that value starts with X (which can be something like _"jenkins-infra/github-reusable-workflows/.github/workflows/maven-cd.yml"_, etc).

this is what I was looking for ^ when I asked about the sections in the code. Based on these sections you can try to decide which one needs to stay in the `ContinuousDeliveryProbe.java` file and which one needs to go to `AbstractGitHubWorkflowProbe.java.

**Comment by alecharp** [comment]
> And this is the foundation of what Adrien suggested above if I'm not wrong (@alecharp please correct me if I'm wrong).

Absolutely correct. 

The two probe requires the same things, have the same condition to be executed and should be executed after the same one. 
The only difference between the two probes is the link to the workflow definition (the `uses`).

The records defined in the `ContinuousDeliveryProbe` are useful for the two probes and should be extracted in the new abstract one. 

> which is what Adrien described above if I'm not wrong.

Not wrong.

**Comment by Jagrutiti** [comment]
> The only difference between the two probes is the link to the workflow definition (the uses).

We can pass the difference using a parameter.

**Comment by Jagrutiti** [comment]
Also, I wanted to start with the test cases first. 
Instead of starting straight away with `abstract` classes and making changes in the current working probe.
