### ISSUE TITLE
Add scores and categories for individual probes

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/plugin-health-scoring#264]
Help me understand what's a problem and how much, by providing, for individual probes:

* The top-level category they count towards
* Their individual score
* (If applicable) their weight of contribution to their top-level category

**Comment by alecharp** [comment]
After discussion with you (Daniel), I do understand your point. 
So, the requirement here is to have a way to understand why a scoring implementation gets a specific score.
For now, only the description can lead to some understanding about the value of the score, but it is not clear enough at all.

We need to see directly how a plugin maintainer can change a score from `0` to `1` or from `0.65` to `1` by addressing specific probes.
This is also true to understand why we have a `1`.
