### ISSUE TITLE
Probe for unreleased commits

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/plugin-health-scoring#265]
### Description

Add a probe for unreleased commits. Unreleased commits (depending on their age, and excluding "prepare for next" m-r-p) are bad.

(Old unreleased commits are worse than very recent unreleased commits, which is different from how the adoption probe handles them.)

**Comment by alecharp** [comment]
For the record, this should include commits on production files only.
This should also be updating the `AdoptionScoring` to remove the date computation from it, and be a separate scoring implementation.
