### ISSUE TITLE
Dependabot suspended should score same as dependabot not enabled

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/plugin-health-scoring#293]
### Description of the bug

Some plugins have dependabot configured but dependabot evaluation of updates has been suspended.  See https://github.com/jenkinsci/branch-api-plugin/pull/360 for an example.  The plugin maintainers are not responding to dependabot pull requests.  When dependabot detects that, it suspends further evaluations.  Dependabot enabled and suspended seems like it should be treated as badly as if dependabot were not configured.

![screencapture-github-jenkinsci-branch-api-plugin-pull-360-2023-04-14-06_35_42-edit](https://user-images.githubusercontent.com/156685/232045339-ba6e1181-b764-411d-bd16-08eee66768e4.png)

**Comment by alecharp** [comment]
I cannot see the warning in the pull request you pointed. That one was closed by dependabot because a new one was created.

Having open dependabot pull requests is cancelling the "good point" of having dependabot configured. Shouldn't this be enough?

**Comment by MarkEWaite** [comment]
> Having open dependabot pull requests is cancelling the "good point" of having dependabot configured. Shouldn't this be enough?

I was thinking that there may be more levels of dependabot scored in a repository, like:

1. Dependabot not enabled
2. Dependabot enabled but suspended due to inactivity on open dependabot pull requests
3. Dependabot enabled with open dependabot pull requests
4. Dependabot enabled with no open dependabot pull requests

I think you're saying that there is no difference in the current scoring between items 1, 2, and 3.  That seems fine to me so long as maintainers understand and accept a temporary drop in their score while dependabot pull requests are being built and reviewed.

**Comment by alecharp** [comment]
Yes for now, scenarios 1, 2 and 3 are the same: they don't grant any point.

**Comment by MarkEWaite** [comment]
> Yes for now, scenarios 1, 2 and 3 are the same: they don't grant any point.

Thanks.  Then this idea is already covered.  Closing
