### ISSUE TITLE
Improve the current CONTRIBUTING.adoc document in docs/

### ISSUE THREAD

**Issue by krisstern** [jenkins-infra/plugin-health-scoring#318]
Regarding the [CONTRIBUTING.adoc](https://github.com/jenkins-infra/plugin-health-scoring/blob/main/docs/CONTRIBUTING.adoc) document there is a lot that is not very clear regarding details of how to set the following up explicitly:
1. PostgreSQL Database
2. GitHub App
3. the environment variables

I have tried to go through the steps as suggested, but it became clear to me that maybe a bit more details should be added to facilitate any newcomers to contribute to the project later?

**Comment by krisstern** [comment]
I will follow up with a PR later.

**Comment by krisstern** [comment]
I am working on this

**Comment by PiyushAryan** [comment]
Hey, @krisstern can you please assign me this issue as I am very new open source and this will be very helpful in my learning about Open Source Contribution.

**Comment by krisstern** [comment]
Hi @PiyushAryan I am working on this and will submit a PR over the winter holidays. Also, we do not assign issues due to bad experience with this practice.
