### ISSUE TITLE
`@Nonnull` and `@CheckForNull` replacement

### ISSUE THREAD

**Issue by alecharp** [jenkins-infra/plugin-health-scoring#322]
### Description

Annotations `@Nonnull` and `@CheckForNull` (part of JSR-305) have been [deprecated since 2016](https://jcp.org/en/jsr/detail?id=305).
They should be replaced with SpotBugs annotation.

More detailed description can be find at https://www.jenkins.io/doc/developer/tutorial-improve/replace-jsr-305-annotations/.

**Comment by Jagrutiti** [comment]
Hi

Here I have to check only the  SpotBugs annotation configuration like here:
 https://www.jenkins.io/doc/developer/tutorial-improve/add-more-spotbugs-checks/#increase-spotbugs-checks?
 
 or do I have to also check whether `@Nonnull` and `@CheckForNull` are not released in any code files? If I have to do this, I think I have to look for a library to read the annotations? I am not sure though.

**Comment by Jagrutiti** [comment]
Discussed the approach for this probe with @aneveux 

I have to look for the following statements in the `.java` files:

`import javax.annotation.Nonnull` 
`import javax.annotation.CheckForNull`
