### ISSUE TITLE
Put in place a periodic export of scores to be consumed by plugin-site

### ISSUE THREAD

**Issue by hervelemeur** [jenkins-infra/plugin-health-scoring#373]
> I was also thinking about putting in place a periodic export of plugin health scores like what's done in https://github.com/jenkins-infra/infra-reports so the plugin site could retrieve these scores from the same place instead of directly querying the plugin health score API. Then even if the plugin health score is down previous scores could be displayed.

> WDYT?

_Originally posted by @lemeurherve in https://github.com/jenkins-infra/plugin-site/issues/1337#issuecomment-1515957842_

**Comment by alecharp** [comment]
so technically, we could have somewhere in the infra a cron doing a curl to the `/api/scores` endpoint of the application to do so. Then, it's a matter of using that "somewhere" in the plugin-site code.

**Comment by lemeurherve** [comment]
Exactly 🙂

**Comment by lemeurherve** [comment]
This would reduce the need of high availability for this API.

**Comment by lemeurherve** [comment]
Can it be the case? In a job from another branch for example?

**Comment by alecharp** [comment]
because the lifecycle of the application is not linked to Jenkins run and it should not be.
