### ISSUE TITLE
Unhandled IO Exception Error in the Probe.

### ISSUE THREAD

**Issue by AayushSaini101** [jenkins-infra/plugin-health-scoring#419]
### Description of the bug

After running the **mvn clean install**. I am getting the below message. 

<img width="1705" alt="image" src="https://github.com/jenkins-infra/plugin-health-scoring/assets/60972989/d510611c-65ea-4b61-b487-186579b19f29">
Error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project plugin-health-scoring-core: Compilation failure
[ERROR] /Users/aaayush/Desktop/plugin-health-scoring/core/src/main/java/io/jenkins/pluginhealth/scoring/probes/Probe.java:[57,27] unreported exception java.io.IOException; must be caught or declared to be thrown

```

**Comment by krisstern** [comment]
I ran `mvn package -Dmaven.test.skip` and my build seems successful:

<img width="679" alt="Screenshot 2023-12-24 at 2 41 06 PM" src="https://github.com/jenkins-infra/plugin-health-scoring/assets/88480540/2a53c83a-1872-4064-843e-b9405246fe62">

**Comment by krisstern** [comment]
Also works if I do `mvn verify` as well:

<img width="456" alt="Screenshot 2023-12-24 at 3 00 47 PM" src="https://github.com/jenkins-infra/plugin-health-scoring/assets/88480540/e917bc20-6467-41a4-ba77-f6d9be2dbc1d">

**Comment by krisstern** [comment]
For more info on how to start, please see https://github.com/jenkins-infra/plugin-health-scoring/blob/main/docs/CONTRIBUTING.adoc.
