### ISSUE TITLE
Need test cases for the IndexController in Plugin-Health-Scoring

### ISSUE THREAD

**Issue by AayushSaini101** [jenkins-infra/plugin-health-scoring#424]
### Description of the bug

At present there is no test case for the Index-Controller in the Plugin-health-scoring. 
<img width="347" alt="image" src="https://github.com/jenkins-infra/plugin-health-scoring/assets/60972989/d9160f13-dd68-4dbe-9fb5-cb14e0189e8a">

Need to add test cases for this controller.

**Comment by alecharp** [comment]
Even if I tend to see test as a must have, the IndexController is only redirecting to the ProbeController and the web access of the application was a small band-aid until the plugins.jenkins.io was integrating the scores computed here.
