### ISSUE TITLE
Probe to check whether the plugin contains  checkstyle configuration or not.

### ISSUE THREAD

**Issue by AayushSaini101** [jenkins-infra/plugin-health-scoring#425]
### Description

Description: 

Need a new probe to check whether the plugin contains check style configuration or not in the repo.

**Comment by alecharp** [comment]
Checkstyle is not configured in the plugin parent POM and is not even described on https://www.jenkins.io/doc/developer/tutorial-improve/. 

I'm not comfortable with adding a probe for some I wouldn't want to use in a scoring later on.

For now, I prefer to close this. We can revisit that decision if someone brings additional argument to this probe.
