### ISSUE TITLE
Plugin description migration probe

### ISSUE THREAD

**Issue by AayushSaini101** [jenkins-infra/plugin-health-scoring#427]
### Description

In the past, it was also possible to provide it using the description tag in plugin POM, but recent versions of the parent POM require the preferred location and will fail to compile if the plugin description is not available from index.jelly in the expected directory.

Reference: https://www.jenkins.io/doc/developer/tutorial-improve/move-description-to-index/

This probe helps to identify which plugin needs improvement to migrate the tag

**Comment by AayushSaini101** [comment]
@alecharp I guess we can confirm by only checking whether the <description> tag is present in the pom.xml or not ?

**Comment by alecharp** [comment]
Not only. The description in the pom can still be present, but we must check the content of the `index.jelly` file and see if it matches the `hello-world` example. 
See https://issues.jenkins.io/browse/JENKINS-68300
