### ISSUE TITLE
New Probe to find the Active Maintainer on the plugin.

### ISSUE THREAD

**Issue by AayushSaini101** [jenkins-infra/plugin-health-scoring#431]
### Description

Need to new probe which maintainer is majorly active on the plugin.

How we can decide on the active Maintainer:
* Number of recently approve request by the maintainer. 
* Number of recently pull request made by the maintainer.
* Number of recently open issue by the maintainer.

Impact:
* Help the stakeholder to connect the suitable maintainer so that they can tag and ask questions easily.

**Comment by alecharp** [comment]
That list exists on https://github.com/jenkins-infra/repository-permissions-updater.
What would be the benefit of having that list to score the plugins?

**Comment by AayushSaini101** [comment]
> That list exists on https://github.com/jenkins-infra/repository-permissions-updater. What would be the benefit of having that list to score the plugins?

The contributor can easily identify which maintainer is active on the plugin. So that they can easily connect him/her easily. This is kind of information not for contributing any scores

**Comment by alecharp** [comment]
> The contributor can easily identify which maintainer is active on the plugin. So that they can easily connect him/her easily. This is kind of information not for contributing any scores

This is already present in plugins.jenkins.io.

**Comment by AayushSaini101** [comment]
> Reference in new issue

@alecharp https://github.com/jenkins-infra/plugin-health-scoring/issues/233 is this same probe ?

**Comment by alecharp** [comment]
Also yes.
