### ISSUE TITLE
Probe to detect whether the pull_request_template.md is present in the plugins.

### ISSUE THREAD

**Issue by AayushSaini101** [jenkins-infra/plugin-health-scoring#435]
### Description

Probe to detect whether the pull_request_template.md is present in the plugins.

Benefits:
* Help the contributors understand the prerequisite for the particular plugin 
* Help identify the area that needs to be updated while making PR on the plugin.

**Comment by alecharp** [comment]
To be fair, the pull request template is not enforcing anything. See, even on this project, some pull request authors removes most of the template when they probably shouldn't.
The most important thing in my opinion is the contributing guide, which is by default inherited from the `jenkinsci/.github` repository. 

That repository already have a pull request template but I cannot find documentation if it's inherited or not in the repository of the organization.

**Comment by AayushSaini101** [comment]
> To be fair, the pull request template is not enforcing anything. See, even on this project, some pull request authors removes most of the template when they probably shouldn't. The most important thing in my opinion is the contributing guide, which is by default inherited from the `jenkinsci/.github` repository.
> 
> That repository already have a pull request template but I cannot find documentation if it's inherited or not in the repository of the organization.

Thanks for your opinion, but ideally case it helps the new contributors as well as maintainers suppose they are making the changes and the repository has no template and the maintainer merged the changes [ that might be possible], without proper additional test cases.
If the template contains the check the feat: changes must require test cases, then it automatically helps the maintainers to check whether the PR contains the test cases or not. 

" some pull request authors removes most of the template when they probably shouldn't." we can improve this by using probe. It helps the stability of the plugins
