### ISSUE TITLE
Improve Plugin Scoring implementation 

### ISSUE THREAD

**Issue by AayushSaini101** [jenkins-infra/plugin-health-scoring#448]
Description: 
At present now, we have several probes that detect the major https://www.jenkins.io/doc/developer/tutorial-improve/ improvement needed in the plugin.
* IncrementalBuildDetectionProbe
* SCMLinkValidationProbe
* JenkinsCoreProbe
* DescriptionProbe [ Issue is already created working on it]
* Add Contribution Guide

These are the same probes that help to detect the major improvements in the plugin, but currently there is no scoring key that helps to identify the improvements needed in the plugin.

<img width="1826" alt="image" src="https://github.com/jenkins-infra/plugin-health-scoring/assets/60972989/5fba16e6-05be-4b9a-981a-9095e2e21d81">

**Comment by alecharp** [comment]
See #243

**Comment by AayushSaini101** [comment]
@alecharp This one is different that https://github.com/jenkins-infra/plugin-health-scoring/issues/243 is related to the Scoring of the quality but this is for to show the area improvement

**Comment by alecharp** [comment]
It can seem different but it is not. We need to rework the current `PluginMaintenanceScoring` to better track the plugin modernization / maintenance guide.
