### ISSUE TITLE
Probe to check whether the release drafter is present or not in the plugin 

### ISSUE THREAD

**Issue by AayushSaini101** [jenkins-infra/plugin-health-scoring#449]
### Description

Release Drafter is a tool and GitHub app which helps to automate the management of releases notes, and it is also a tasks in the plugin modernalisation, so it would be good to make a probe to detect whether the Release drafter is present or not in the plugin.

**Comment by AayushSaini101** [comment]
@alecharp Please check this issue, So that i can start working on it

**Comment by alecharp** [comment]
@AayushSaini101 It's a good idea.
