### ISSUE TITLE
Need Renaming or add proper test for shouldRequireValidSCMAndLastCommit in DependabotProbeTest

### ISSUE THREAD

**Issue by AayushSaini101** [jenkins-infra/plugin-health-scoring#460]
Currently the naming of test method is seems to confusing that is 
<img width="1248" alt="image" src="https://github.com/jenkins-infra/plugin-health-scoring/assets/60972989/37e21ff2-a0a1-45ac-b124-a1385a1fc9cd">
In this test method we are only validating the repository not last commit void shouldRequireValidSCMAndLastCommit() { }

**Comment by alecharp** [comment]
Screenshots of code are not helpful. Providing links would be simpler.
