### ISSUE TITLE
Add new scoring for the release-drafter probe.

### ISSUE THREAD

**Issue by AayushSaini101** [jenkins-infra/plugin-health-scoring#461]
After Merging: https://github.com/jenkins-infra/plugin-health-scoring/pull/453, We need to introduce the new scoring for the release-drafter probe.

**Comment by alecharp** [comment]
This is the one that needs to be simplified a lot. Its maintenance is the worse.

**Comment by AayushSaini101** [comment]
> This is the one that needs to be simplified a lot. Its maintenance is the worst.

@alecharp Can you tell what kind of improvements is needed in this scoring ? First thing i noted here the naming is not proper the name is PluginMaintenanceScoring but the key used is repository-configuration which is not making any sense

**Comment by AayushSaini101** [comment]
> Not as simple. The probe need to be including in an existing or a new scoring. Yes. We need to see how we can intelligently group probes so that their combined result is meaningful.

@alecharp we can make separate group for the probes that work for the quality of the plugin.https://github.com/jenkins-infra/plugin-health-scoring/issues/243 we can add in this issue
