### ISSUE TITLE
Renovate probe doesn't detect all supported config file names

### ISSUE THREAD

**Issue by viceice** [jenkins-infra/plugin-health-scoring#483]
### Description of the bug

I've my renovate configs in repo root, which is allowed by renovate and isn't detected by the renovate probe.

- https://github.com/renovatebot/renovate/blob/b92afa4bd436d6725c4daef7a29d79335eb9f419/lib/config/app-strings.ts#L1
- https://github.com/jenkinsci/scoring-load-balancer-plugin/blob/main/renovate.json
- https://github.com/jenkinsci/additional-identities-plugin/blob/main/renovate.json
- https://groups.google.com/g/jenkinsci-dev/c/l6WwouOW4KY

Will now move to `.github` folder to workaround

**Comment by alecharp** [comment]
Thank you for bringing that to my attention. 
I'll make sure to fix that as soon as possible.

**Comment by alecharp** [comment]
@viceice when you have a moment, please have a look at the pull request linked to see if the fix sounds acceptable to you. Thanks.
