### ISSUE TITLE
Documentation scoring should probably not consider "contributing guidelines" inheritance as an issue

### ISSUE THREAD

**Issue by PierreBtz** [jenkins-infra/plugin-health-scoring#487]
### Description of the bug

Currently, inheriting from the global contributing guidelines of the jenkinsci organization is considered an issue reducing the documentation score of a plugin. See for instance [this plugin](https://plugins.jenkins.io/cloudbees-jenkins-advisor/healthscore/):

![Screenshot 2024-03-15 at 16 12 45](https://github.com/jenkins-infra/plugin-health-scoring/assets/9881659/906bc673-ef88-477d-bc46-44e0000a4f11)

There are several issues with this approach:

1. it can be easily cheesed by simply adding contributions guideline that are linking back (or worst that are a copy) of the org ones.
2. contribution guideline should ideally be the same for each plugin, an incentive to override this per repository goes against this.

**Comment by alecharp** [comment]
While I agree that losing points over this when the global contributing guide is valid for the vast majority of the plugins is a shame.

> contribution guideline should ideally be the same for each plugin, an incentive to override this per repository goes against this.

I would argue that some plugins have specific requirements (UI, API plugins) which would be nice to see in a specific contributing guide.

We could fix the situation with:
1. using global contributing guide is fine (no point lost)
2. have a specific one is better (extra credit?)
3. empty contributing guide is bad.

Does this make sense to you?

**Comment by PierreBtz** [comment]
Looks good!
