### ISSUE TITLE
Add a date to the plugin scores JSON

### ISSUE THREAD

**Issue by zbynek** [jenkins-infra/plugin-health-scoring#489]
### Description of the bug

As a plugin site visitor I'd like to know when was all the information used for generating the report gathered. To have that information in the UI of the plugin site it has to be accessible through the API of plugin health scoring.

**Comment by AayushSaini101** [comment]
We just need to call the value of the computed_id for a particular plugin,
![image](https://github.com/jenkins-infra/plugin-health-scoring/assets/60972989/d5190db3-fbbb-4555-bc93-59293befeaee)

**Comment by alecharp** [comment]
I think this is reasonable. It's something that is displayed on the app webpage but not in plugins.jenkins.io.

@zbynek Would you prefer to have the timestamp of the overall score computation only or for each individual section? Those can be different.

**Comment by zbynek** [comment]
> Would you prefer to have the timestamp of the overall score computation only or for each individual section?

One timestamp should be enough, thanks.

**Comment by alecharp** [comment]
I made a pull request which should provide the required data. Please see the json format on the test.
