### ISSUE TITLE
Health Score Not getting updated.

### ISSUE THREAD

**Issue by rahuldarekar222** [jenkins-infra/plugin-health-scoring#523]
### Description of the bug

Hi Team,
Health score not getting updated though all conditions are met for Secone Security Plugin.

link for the plugin:  https://plugins.jenkins.io/secone-security/healthscore/
PFA screenshot of plugin page. There are no PR which are in open state but still out score is 50% for Pr section.
"Dependabot is configured.
2 open dependency pull request"

let us know if you require more information.
![Screenshot 2024-07-03 at 12 03 39 PM](https://github.com/jenkins-infra/plugin-health-scoring/assets/139219289/374eece8-1967-4e6f-8849-6057a245b44c)

**Comment by alecharp** [comment]
Already tracked in #522
