### ISSUE TITLE
Sort probes in UI based on execution order or name

### ISSUE THREAD

**Issue by alecharp** [jenkins-infra/plugin-health-scoring#65]
Because of 
https://github.com/jenkins-infra/plugin-health-scoring/blob/6f9c5d2363df9599117e310f88f4461f61249ba5/src/main/java/io/jenkins/pluginhealth/scoring/http/ProbesController.java#L55

the probes are listed based on their name. However, it might be good to sort based on their execution order on each plugin. Or to have and indication of the execution order and to be able to sort the list as the user wants.

**Comment by jleon33** [comment]
I agree. We should have a column indicating the execution order and have the ability to sort by name or order.

**Comment by dheerajodha** [comment]
For this, I tried using something like the [datatables](https://www.datatables.net/) tool.
I tried to add it to the table present at `/probes` view and this tool makes it look like this:

![Untitled](https://user-images.githubusercontent.com/43273420/201517867-f98667e2-054e-4080-8fa7-a5489caef8cd.gif)

wdyt?

**Comment by hervelemeur** [comment]
What's the behavior of this table when there is more than one page of results?

**Comment by dheerajodha** [comment]
@hervelemeur I tried adding a few more dummy probes to make it a total of 32 to be listed on this page.
In that case, the table listed 10 by default on the first page and moved the others to the next pages.
But when I change "Show x entries" from 10 to 25, the first 25 of them get listed on the first page. See:
![Untitled (1)](https://user-images.githubusercontent.com/43273420/201534593-a76a4d9f-f02c-4ca8-9c29-a91e87b35d34.gif)

**Comment by alecharp** [comment]
Please open your pull request so we can discuss their about styling a bit the different components (buttons, textboxes, dropdown) so they integrate a bit better.

**Comment by lemeurherve** [comment]
> @hervelemeur I tried adding some more `up-for-adoption` probes to make it a total of 32 to be listed on this page. In that case, the table listed 10 by default on the first page and moved the others to the next pages. But when I change "Show x entries" from 10 to 25, the first 25 of them get listed on the first page. See: ![Untitled (1)](https://user-images.githubusercontent.com/43273420/201534593-a76a4d9f-f02c-4ca8-9c29-a91e87b35d34.gif) [ ![Untitled (1)](https://user-images.githubusercontent.com/43273420/201534593-a76a4d9f-f02c-4ca8-9c29-a91e87b35d34.gif) ](https://user-images.githubusercontent.com/43273420/201534593-a76a4d9f-f02c-4ca8-9c29-a91e87b35d34.gif) [ ](https://user-images.githubusercontent.com/43273420/201534593-a76a4d9f-f02c-4ca8-9c29-a91e87b35d34.gif)

What I want to know is when you have more than one page of results and try to sort on "Name" for example, does it sorts all results or only the ones displayed in the current page? (ie: does it sort only client side which wouldn't be enough?)

**Comment by dheerajodha** [comment]
> What I want to know is when you have more than one page of results and try to sort on "Name" for example, does it sorts all results or only the ones displayed in the current page? (ie: does it sorts only client side which wouldn't be enough, a common gotcha?)

Oh I see, yes, it sorts all the results present in the whole table (and not just on the current page).

> Please open your pull request so we can discuss their about styling a bit the different components (buttons, textboxes, dropdown) so they integrate a bit better.

Done, thanks!
