### ISSUE TITLE
Select which plugin we want to run the probes on

### ISSUE THREAD

**Issue by alecharp** [jenkins-infra/plugin-health-scoring#67]
For now, we are running all the probes on all the plugins. However, it would be great to be able to run the probes on a specific plugin. 
This would be useful for example to have a pipeline step in ci.jenkins.io to re-ran the probes on the main branch of the plugin to re-run probes which don't require a new release.

**Comment by jleon33** [comment]
Is this different from issue #62 that I made a few days ago? Tangentially related, would we want the ability to run specific probes on a plugin? Say someone makes some changes to address one specific area and they just want to run the probe(s) related to that.

**Comment by alecharp** [comment]
It is not, I didn't see #62. I'll close this current issue.

> Tangentially related, would we want the ability to run specific probes on a plugin?
I don't think it's a good idea. it could change the scoring of a plugin without having a complete picture of the health of it.
