### ISSUE TITLE
Update Center data should be read once a day

### ISSUE THREAD

**Issue by alecharp** [jenkins-infra/plugin-health-scoring#9]
The current implementation read the `update-center` when the application starts. 
However, we want, in the end, the application to run all the time and still read the update-center daily.

We need change the current behavior so that we can read the data without restarting the application.

- [ ] The delay between updates should be configurable
- [ ] The updates shouldn't require the application to restart

**Comment by dheerajodha** [comment]
So if we talk about the current status of the project, how does the following solution sound to you?

Step 1) We start our spring boot project and as per the logic of the code, we run the `readUpdateCenter` method which reads the update-center and fetches plugins, and stores them into the empty DB.

Step 2) 30 seconds later (from the time when we were done saving plugins into the DB, from the previous step), we again call the `readUpdateCenter` method. (Remember the project is still running, we haven't restarted it)

Step 3) Go to Step 2.

As per my understanding, out of the two tasks you have mentioned in this issue, the above 3-step approach might be able to fulfill the requirements. What do you think?

**Comment by alecharp** [comment]
We could want to update application only on monday, or every day at 2am or every 24hr. I'm not sure your approach could provide us this.

> as per the logic of the code

the code can be changed, altered, deleted completely. Please remind that nothing is definitive. 

Overall, I think you get what needs to be done. Please have a look at Batch, this could be want we need.
