### ISSUE TITLE
Expand JEP-229 file pattern for .yaml extension

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/plugin-health-scoring#91]
The recent addition of the JEP-229 probe looks for `cd.yml` files only, but there are almost 60 `cd.yaml` files

https://github.com/jenkins-infra/plugin-health-scoring/blob/a28c74219679b64e42f72207a08ae02b9b1ca15e/src/main/java/io/jenkins/pluginhealth/scoring/probes/ContinuousDeploymentProbe.java#L53

https://cs.github.com/?scopeName=All+repos&scope=&q=org%3Ajenkinsci+cd.yaml

**Comment by alecharp** [comment]
Thanks @NotMyFault for catching this. I created a pull request to try to solve this.
