### ISSUE TITLE
Update plugin-health.jenkins.io/probes to include the total raw data of the probes

### ISSUE THREAD

**Issue by jleon33** [jenkins-infra/plugin-health-scoring#96]
As it stands right now with the probes we have, of the 1881 plugins:

120 are up for adoption
178 have public security issues
32 are deprecated
442 are configured with Dependabot
71 are configured with JEP-229 (continuous delivery - looking deeper into this one, seems too low)
1156 have a Jenkinsfile

It would be nice to see this data on that webpage maybe in its own column.

**Comment by alecharp** [comment]
To be honest, I would prefer to have this displayed in a different view as it would display the result of the probes on the plugins we know.

**Comment by jleon33** [comment]
Agreed. That sounds better

**Comment by dheerajodha** [comment]
If this issue is up for grabs, can I work on it?

**Comment by alecharp** [comment]
> If this issue is up for grabs, can I work on it?

yes it is.
